#!/usr/bin/env python3
"""
Fallback country data when API is unavailable.
Contains essential data for 200+ countries.
"""

import json
from pathlib import Path

DATA_DIR = Path(__file__).parent.parent / "data"

# Complete list of countries with solo travel data
COUNTRIES = [
    # Asia
    {"name": "Japan", "capital": "Tokyo", "region": "Asia", "subregion": "Eastern Asia", "population": 125800000, "currency": "Japanese Yen (JPY)", "language": "Japanese", "timezone": "UTC+9", "safety_level": "safe", "best_time": "Mar-May, Oct-Nov", "budget": {"budget": "70-100", "midrange": "120-180", "luxury": "350+"}, "featured": True},
    {"name": "Thailand", "capital": "Bangkok", "region": "Asia", "subregion": "South-Eastern Asia", "population": 69800000, "currency": "Thai Baht (THB)", "language": "Thai", "timezone": "UTC+7", "safety_level": "caution", "best_time": "Nov-Feb", "budget": {"budget": "30-45", "midrange": "60-100", "luxury": "200+"}, "featured": True},
    {"name": "Vietnam", "capital": "Hanoi", "region": "Asia", "subregion": "South-Eastern Asia", "population": 97340000, "currency": "Vietnamese Dong (VND)", "language": "Vietnamese", "timezone": "UTC+7", "safety_level": "caution", "best_time": "Feb-Apr, Aug-Oct", "budget": {"budget": "20-30", "midrange": "40-60", "luxury": "100+"}, "featured": True},
    {"name": "Indonesia", "capital": "Jakarta", "region": "Asia", "subregion": "South-Eastern Asia", "population": 273500000, "currency": "Indonesian Rupiah (IDR)", "language": "Indonesian", "timezone": "UTC+7 to +9", "safety_level": "caution", "best_time": "Apr-Oct", "budget": {"budget": "25-35", "midrange": "50-80", "luxury": "150+"}, "featured": True},
    {"name": "Malaysia", "capital": "Kuala Lumpur", "region": "Asia", "subregion": "South-Eastern Asia", "population": 32370000, "currency": "Malaysian Ringgit (MYR)", "language": "Malay", "timezone": "UTC+8", "safety_level": "safe", "best_time": "Year-round", "budget": {"budget": "35-50", "midrange": "60-100", "luxury": "180+"}, "featured": False},
    {"name": "Singapore", "capital": "Singapore", "region": "Asia", "subregion": "South-Eastern Asia", "population": 5850000, "currency": "Singapore Dollar (SGD)", "language": "English", "timezone": "UTC+8", "safety_level": "safe", "best_time": "Year-round", "budget": {"budget": "80-110", "midrange": "140-220", "luxury": "400+"}, "featured": True},
    {"name": "Philippines", "capital": "Manila", "region": "Asia", "subregion": "South-Eastern Asia", "population": 109580000, "currency": "Philippine Peso (PHP)", "language": "Filipino", "timezone": "UTC+8", "safety_level": "caution", "best_time": "Dec-May", "budget": {"budget": "25-40", "midrange": "50-80", "luxury": "120+"}, "featured": False},
    {"name": "Cambodia", "capital": "Phnom Penh", "region": "Asia", "subregion": "South-Eastern Asia", "population": 16720000, "currency": "Cambodian Riel (KHR)", "language": "Khmer", "timezone": "UTC+7", "safety_level": "caution", "best_time": "Nov-Apr", "budget": {"budget": "20-30", "midrange": "40-60", "luxury": "80+"}, "featured": False},
    {"name": "Laos", "capital": "Vientiane", "region": "Asia", "subregion": "South-Eastern Asia", "population": 7280000, "currency": "Lao Kip (LAK)", "language": "Lao", "timezone": "UTC+7", "safety_level": "caution", "best_time": "Nov-Feb", "budget": {"budget": "20-30", "midrange": "35-50", "luxury": "70+"}, "featured": False},
    {"name": "Myanmar", "capital": "Naypyidaw", "region": "Asia", "subregion": "South-Eastern Asia", "population": 54410000, "currency": "Myanmar Kyat (MMK)", "language": "Burmese", "timezone": "UTC+6:30", "safety_level": "warning", "best_time": "Nov-Feb", "budget": {"budget": "25-35", "midrange": "45-70", "luxury": "100+"}, "featured": False},
    {"name": "South Korea", "capital": "Seoul", "region": "Asia", "subregion": "Eastern Asia", "population": 51780000, "currency": "South Korean Won (KRW)", "language": "Korean", "timezone": "UTC+9", "safety_level": "safe", "best_time": "Apr-Jun, Sep-Nov", "budget": {"budget": "60-80", "midrange": "100-150", "luxury": "280+"}, "featured": True},
    {"name": "Taiwan", "capital": "Taipei", "region": "Asia", "subregion": "Eastern Asia", "population": 23570000, "currency": "New Taiwan Dollar (TWD)", "language": "Mandarin", "timezone": "UTC+8", "safety_level": "safe", "best_time": "Oct-Apr", "budget": {"budget": "50-70", "midrange": "80-130", "luxury": "220+"}, "featured": True},
    {"name": "China", "capital": "Beijing", "region": "Asia", "subregion": "Eastern Asia", "population": 1402000000, "currency": "Chinese Yuan (CNY)", "language": "Mandarin", "timezone": "UTC+8", "safety_level": "caution", "best_time": "Apr-May, Sep-Oct", "budget": {"budget": "40-60", "midrange": "80-130", "luxury": "200+"}, "featured": False},
    {"name": "Hong Kong", "capital": "Hong Kong", "region": "Asia", "subregion": "Eastern Asia", "population": 7482000, "currency": "Hong Kong Dollar (HKD)", "language": "Cantonese", "timezone": "UTC+8", "safety_level": "safe", "best_time": "Oct-Dec", "budget": {"budget": "70-100", "midrange": "130-200", "luxury": "350+"}, "featured": False},
    {"name": "India", "capital": "New Delhi", "region": "Asia", "subregion": "Southern Asia", "population": 1380000000, "currency": "Indian Rupee (INR)", "language": "Hindi", "timezone": "UTC+5:30", "safety_level": "caution", "best_time": "Oct-Mar", "budget": {"budget": "20-35", "midrange": "40-70", "luxury": "120+"}, "featured": True},
    {"name": "Nepal", "capital": "Kathmandu", "region": "Asia", "subregion": "Southern Asia", "population": 29140000, "currency": "Nepalese Rupee (NPR)", "language": "Nepali", "timezone": "UTC+5:45", "safety_level": "caution", "best_time": "Oct-Nov, Mar-May", "budget": {"budget": "20-30", "midrange": "40-60", "luxury": "100+"}, "featured": False},
    {"name": "Sri Lanka", "capital": "Colombo", "region": "Asia", "subregion": "Southern Asia", "population": 21920000, "currency": "Sri Lankan Rupee (LKR)", "language": "Sinhala", "timezone": "UTC+5:30", "safety_level": "caution", "best_time": "Dec-Mar", "budget": {"budget": "25-40", "midrange": "50-80", "luxury": "130+"}, "featured": False},
    {"name": "Bangladesh", "capital": "Dhaka", "region": "Asia", "subregion": "Southern Asia", "population": 164690000, "currency": "Bangladeshi Taka (BDT)", "language": "Bengali", "timezone": "UTC+6", "safety_level": "caution", "best_time": "Nov-Feb", "budget": {"budget": "20-30", "midrange": "35-55", "luxury": "80+"}, "featured": False},
    {"name": "Pakistan", "capital": "Islamabad", "region": "Asia", "subregion": "Southern Asia", "population": 220890000, "currency": "Pakistani Rupee (PKR)", "language": "Urdu", "timezone": "UTC+5", "safety_level": "warning", "best_time": "Oct-Mar", "budget": {"budget": "25-35", "midrange": "45-70", "luxury": "100+"}, "featured": False},
    {"name": "Maldives", "capital": "Male", "region": "Asia", "subregion": "Southern Asia", "population": 540540, "currency": "Maldivian Rufiyaa (MVR)", "language": "Dhivehi", "timezone": "UTC+5", "safety_level": "safe", "best_time": "Nov-Apr", "budget": {"budget": "100-150", "midrange": "200-400", "luxury": "800+"}, "featured": False},

    # Europe
    {"name": "Portugal", "capital": "Lisbon", "region": "Europe", "subregion": "Southern Europe", "population": 10200000, "currency": "Euro (EUR)", "language": "Portuguese", "timezone": "UTC+0", "safety_level": "safe", "best_time": "Apr-Oct", "budget": {"budget": "50-70", "midrange": "90-140", "luxury": "250+"}, "featured": True},
    {"name": "Spain", "capital": "Madrid", "region": "Europe", "subregion": "Southern Europe", "population": 46940000, "currency": "Euro (EUR)", "language": "Spanish", "timezone": "UTC+1", "safety_level": "safe", "best_time": "Apr-Jun, Sep-Oct", "budget": {"budget": "60-80", "midrange": "100-160", "luxury": "300+"}, "featured": True},
    {"name": "Italy", "capital": "Rome", "region": "Europe", "subregion": "Southern Europe", "population": 60360000, "currency": "Euro (EUR)", "language": "Italian", "timezone": "UTC+1", "safety_level": "safe", "best_time": "Apr-Jun, Sep-Oct", "budget": {"budget": "70-90", "midrange": "120-180", "luxury": "350+"}, "featured": True},
    {"name": "France", "capital": "Paris", "region": "Europe", "subregion": "Western Europe", "population": 67390000, "currency": "Euro (EUR)", "language": "French", "timezone": "UTC+1", "safety_level": "caution", "best_time": "Apr-Jun, Sep-Oct", "budget": {"budget": "80-100", "midrange": "140-200", "luxury": "400+"}, "featured": True},
    {"name": "Germany", "capital": "Berlin", "region": "Europe", "subregion": "Western Europe", "population": 83240000, "currency": "Euro (EUR)", "language": "German", "timezone": "UTC+1", "safety_level": "safe", "best_time": "May-Sep", "budget": {"budget": "70-90", "midrange": "110-170", "luxury": "300+"}, "featured": True},
    {"name": "United Kingdom", "capital": "London", "region": "Europe", "subregion": "Northern Europe", "population": 67890000, "currency": "British Pound (GBP)", "language": "English", "timezone": "UTC+0", "safety_level": "caution", "best_time": "May-Sep", "budget": {"budget": "80-110", "midrange": "150-220", "luxury": "400+"}, "featured": True},
    {"name": "Ireland", "capital": "Dublin", "region": "Europe", "subregion": "Northern Europe", "population": 4940000, "currency": "Euro (EUR)", "language": "English", "timezone": "UTC+0", "safety_level": "safe", "best_time": "May-Sep", "budget": {"budget": "70-100", "midrange": "130-190", "luxury": "350+"}, "featured": False},
    {"name": "Netherlands", "capital": "Amsterdam", "region": "Europe", "subregion": "Western Europe", "population": 17440000, "currency": "Euro (EUR)", "language": "Dutch", "timezone": "UTC+1", "safety_level": "safe", "best_time": "Apr-Sep", "budget": {"budget": "80-100", "midrange": "130-190", "luxury": "350+"}, "featured": True},
    {"name": "Belgium", "capital": "Brussels", "region": "Europe", "subregion": "Western Europe", "population": 11590000, "currency": "Euro (EUR)", "language": "Dutch", "timezone": "UTC+1", "safety_level": "safe", "best_time": "May-Sep", "budget": {"budget": "70-90", "midrange": "120-180", "luxury": "320+"}, "featured": False},
    {"name": "Switzerland", "capital": "Bern", "region": "Europe", "subregion": "Western Europe", "population": 8650000, "currency": "Swiss Franc (CHF)", "language": "German", "timezone": "UTC+1", "safety_level": "safe", "best_time": "Jun-Sep, Dec-Mar", "budget": {"budget": "120-160", "midrange": "200-300", "luxury": "550+"}, "featured": True},
    {"name": "Austria", "capital": "Vienna", "region": "Europe", "subregion": "Western Europe", "population": 9010000, "currency": "Euro (EUR)", "language": "German", "timezone": "UTC+1", "safety_level": "safe", "best_time": "Jun-Sep, Dec-Mar", "budget": {"budget": "70-90", "midrange": "120-180", "luxury": "320+"}, "featured": False},
    {"name": "Czech Republic", "capital": "Prague", "region": "Europe", "subregion": "Central Europe", "population": 10700000, "currency": "Czech Koruna (CZK)", "language": "Czech", "timezone": "UTC+1", "safety_level": "safe", "best_time": "May-Sep", "budget": {"budget": "50-70", "midrange": "90-140", "luxury": "250+"}, "featured": True},
    {"name": "Poland", "capital": "Warsaw", "region": "Europe", "subregion": "Central Europe", "population": 37950000, "currency": "Polish Zloty (PLN)", "language": "Polish", "timezone": "UTC+1", "safety_level": "safe", "best_time": "May-Sep", "budget": {"budget": "40-60", "midrange": "70-120", "luxury": "200+"}, "featured": False},
    {"name": "Hungary", "capital": "Budapest", "region": "Europe", "subregion": "Central Europe", "population": 9660000, "currency": "Hungarian Forint (HUF)", "language": "Hungarian", "timezone": "UTC+1", "safety_level": "safe", "best_time": "Apr-Jun, Sep-Oct", "budget": {"budget": "45-65", "midrange": "80-130", "luxury": "220+"}, "featured": False},
    {"name": "Croatia", "capital": "Zagreb", "region": "Europe", "subregion": "Southern Europe", "population": 4050000, "currency": "Euro (EUR)", "language": "Croatian", "timezone": "UTC+1", "safety_level": "safe", "best_time": "May-Sep", "budget": {"budget": "55-75", "midrange": "100-150", "luxury": "280+"}, "featured": True},
    {"name": "Greece", "capital": "Athens", "region": "Europe", "subregion": "Southern Europe", "population": 10420000, "currency": "Euro (EUR)", "language": "Greek", "timezone": "UTC+2", "safety_level": "safe", "best_time": "Apr-Jun, Sep-Oct", "budget": {"budget": "50-70", "midrange": "90-140", "luxury": "250+"}, "featured": True},
    {"name": "Turkey", "capital": "Ankara", "region": "Europe", "subregion": "Western Asia", "population": 84340000, "currency": "Turkish Lira (TRY)", "language": "Turkish", "timezone": "UTC+3", "safety_level": "caution", "best_time": "Apr-May, Sep-Nov", "budget": {"budget": "35-50", "midrange": "70-120", "luxury": "200+"}, "featured": True},
    {"name": "Iceland", "capital": "Reykjavik", "region": "Europe", "subregion": "Northern Europe", "population": 366000, "currency": "Icelandic Krona (ISK)", "language": "Icelandic", "timezone": "UTC+0", "safety_level": "safe", "best_time": "Jun-Aug, Sep-Mar", "budget": {"budget": "130-170", "midrange": "220-320", "luxury": "550+"}, "featured": True},
    {"name": "Norway", "capital": "Oslo", "region": "Europe", "subregion": "Northern Europe", "population": 5420000, "currency": "Norwegian Krone (NOK)", "language": "Norwegian", "timezone": "UTC+1", "safety_level": "safe", "best_time": "Jun-Aug, Dec-Mar", "budget": {"budget": "110-150", "midrange": "180-280", "luxury": "500+"}, "featured": False},
    {"name": "Sweden", "capital": "Stockholm", "region": "Europe", "subregion": "Northern Europe", "population": 10350000, "currency": "Swedish Krona (SEK)", "language": "Swedish", "timezone": "UTC+1", "safety_level": "safe", "best_time": "May-Sep", "budget": {"budget": "100-140", "midrange": "170-260", "luxury": "450+"}, "featured": False},
    {"name": "Denmark", "capital": "Copenhagen", "region": "Europe", "subregion": "Northern Europe", "population": 5830000, "currency": "Danish Krone (DKK)", "language": "Danish", "timezone": "UTC+1", "safety_level": "safe", "best_time": "May-Sep", "budget": {"budget": "100-140", "midrange": "170-260", "luxury": "450+"}, "featured": False},
    {"name": "Finland", "capital": "Helsinki", "region": "Europe", "subregion": "Northern Europe", "population": 5540000, "currency": "Euro (EUR)", "language": "Finnish", "timezone": "UTC+2", "safety_level": "safe", "best_time": "Jun-Aug, Dec-Mar", "budget": {"budget": "100-140", "midrange": "170-250", "luxury": "420+"}, "featured": False},
    {"name": "Estonia", "capital": "Tallinn", "region": "Europe", "subregion": "Northern Europe", "population": 1330000, "currency": "Euro (EUR)", "language": "Estonian", "timezone": "UTC+2", "safety_level": "safe", "best_time": "May-Sep", "budget": {"budget": "50-70", "midrange": "90-140", "luxury": "240+"}, "featured": False},
    {"name": "Latvia", "capital": "Riga", "region": "Europe", "subregion": "Northern Europe", "population": 1880000, "currency": "Euro (EUR)", "language": "Latvian", "timezone": "UTC+2", "safety_level": "safe", "best_time": "May-Sep", "budget": {"budget": "45-65", "midrange": "80-130", "luxury": "220+"}, "featured": False},
    {"name": "Lithuania", "capital": "Vilnius", "region": "Europe", "subregion": "Northern Europe", "population": 2790000, "currency": "Euro (EUR)", "language": "Lithuanian", "timezone": "UTC+2", "safety_level": "safe", "best_time": "May-Sep", "budget": {"budget": "45-65", "midrange": "80-130", "luxury": "220+"}, "featured": False},
    {"name": "Slovenia", "capital": "Ljubljana", "region": "Europe", "subregion": "Southern Europe", "population": 2100000, "currency": "Euro (EUR)", "language": "Slovenian", "timezone": "UTC+1", "safety_level": "safe", "best_time": "May-Sep", "budget": {"budget": "55-75", "midrange": "100-150", "luxury": "280+"}, "featured": True},
    {"name": "Slovakia", "capital": "Bratislava", "region": "Europe", "subregion": "Central Europe", "population": 5460000, "currency": "Euro (EUR)", "language": "Slovak", "timezone": "UTC+1", "safety_level": "safe", "best_time": "May-Sep", "budget": {"budget": "45-65", "midrange": "80-130", "luxury": "220+"}, "featured": False},
    {"name": "Romania", "capital": "Bucharest", "region": "Europe", "subregion": "Southeastern Europe", "population": 19240000, "currency": "Romanian Leu (RON)", "language": "Romanian", "timezone": "UTC+2", "safety_level": "safe", "best_time": "May-Sep", "budget": {"budget": "40-55", "midrange": "70-110", "luxury": "180+"}, "featured": False},
    {"name": "Bulgaria", "capital": "Sofia", "region": "Europe", "subregion": "Southeastern Europe", "population": 6930000, "currency": "Bulgarian Lev (BGN)", "language": "Bulgarian", "timezone": "UTC+2", "safety_level": "safe", "best_time": "May-Sep", "budget": {"budget": "35-50", "midrange": "60-100", "luxury": "160+"}, "featured": False},
    {"name": "Serbia", "capital": "Belgrade", "region": "Europe", "subregion": "Southeastern Europe", "population": 6910000, "currency": "Serbian Dinar (RSD)", "language": "Serbian", "timezone": "UTC+1", "safety_level": "safe", "best_time": "May-Sep", "budget": {"budget": "35-50", "midrange": "60-100", "luxury": "160+"}, "featured": False},
    {"name": "Montenegro", "capital": "Podgorica", "region": "Europe", "subregion": "Southeastern Europe", "population": 628000, "currency": "Euro (EUR)", "language": "Montenegrin", "timezone": "UTC+1", "safety_level": "safe", "best_time": "May-Sep", "budget": {"budget": "50-70", "midrange": "90-140", "luxury": "240+"}, "featured": False},
    {"name": "Bosnia and Herzegovina", "capital": "Sarajevo", "region": "Europe", "subregion": "Southeastern Europe", "population": 3280000, "currency": "Convertible Mark (BAM)", "language": "Bosnian", "timezone": "UTC+1", "safety_level": "safe", "best_time": "May-Sep", "budget": {"budget": "35-50", "midrange": "60-100", "luxury": "160+"}, "featured": False},
    {"name": "Albania", "capital": "Tirana", "region": "Europe", "subregion": "Southeastern Europe", "population": 2880000, "currency": "Albanian Lek (ALL)", "language": "Albanian", "timezone": "UTC+1", "safety_level": "caution", "best_time": "May-Sep", "budget": {"budget": "35-50", "midrange": "60-100", "luxury": "160+"}, "featured": False},
    {"name": "North Macedonia", "capital": "Skopje", "region": "Europe", "subregion": "Southeastern Europe", "population": 2080000, "currency": "Macedonian Denar (MKD)", "language": "Macedonian", "timezone": "UTC+1", "safety_level": "safe", "best_time": "May-Sep", "budget": {"budget": "30-45", "midrange": "55-90", "luxury": "150+"}, "featured": False},
    {"name": "Malta", "capital": "Valletta", "region": "Europe", "subregion": "Southern Europe", "population": 514000, "currency": "Euro (EUR)", "language": "Maltese", "timezone": "UTC+1", "safety_level": "safe", "best_time": "Apr-Jun, Sep-Nov", "budget": {"budget": "60-80", "midrange": "100-160", "luxury": "300+"}, "featured": False},
    {"name": "Cyprus", "capital": "Nicosia", "region": "Europe", "subregion": "Eastern Europe", "population": 1210000, "currency": "Euro (EUR)", "language": "Greek", "timezone": "UTC+2", "safety_level": "safe", "best_time": "Apr-Jun, Sep-Nov", "budget": {"budget": "55-75", "midrange": "100-150", "luxury": "280+"}, "featured": False},
    {"name": "Luxembourg", "capital": "Luxembourg", "region": "Europe", "subregion": "Western Europe", "population": 634000, "currency": "Euro (EUR)", "language": "Luxembourgish", "timezone": "UTC+1", "safety_level": "safe", "best_time": "May-Sep", "budget": {"budget": "100-130", "midrange": "170-250", "luxury": "450+"}, "featured": False},
    {"name": "Monaco", "capital": "Monaco", "region": "Europe", "subregion": "Western Europe", "population": 39240, "currency": "Euro (EUR)", "language": "French", "timezone": "UTC+1", "safety_level": "safe", "best_time": "Year-round", "budget": {"budget": "150-200", "midrange": "300-500", "luxury": "1000+"}, "featured": False},

    # Americas
    {"name": "United States", "capital": "Washington D.C.", "region": "Americas", "subregion": "Northern America", "population": 331000000, "currency": "US Dollar (USD)", "language": "English", "timezone": "UTC-5 to -10", "safety_level": "caution", "best_time": "Varies by region", "budget": {"budget": "90-120", "midrange": "160-250", "luxury": "450+"}, "featured": True},
    {"name": "Canada", "capital": "Ottawa", "region": "Americas", "subregion": "Northern America", "population": 38010000, "currency": "Canadian Dollar (CAD)", "language": "English", "timezone": "UTC-3.5 to -8", "safety_level": "safe", "best_time": "Jun-Sep, Dec-Mar", "budget": {"budget": "80-110", "midrange": "140-220", "luxury": "400+"}, "featured": True},
    {"name": "Mexico", "capital": "Mexico City", "region": "Americas", "subregion": "Central America", "population": 128900000, "currency": "Mexican Peso (MXN)", "language": "Spanish", "timezone": "UTC-6 to -8", "safety_level": "caution", "best_time": "Dec-Apr", "budget": {"budget": "35-50", "midrange": "70-120", "luxury": "200+"}, "featured": True},
    {"name": "Costa Rica", "capital": "San Jose", "region": "Americas", "subregion": "Central America", "population": 5090000, "currency": "Costa Rican Colon (CRC)", "language": "Spanish", "timezone": "UTC-6", "safety_level": "caution", "best_time": "Dec-Apr", "budget": {"budget": "45-60", "midrange": "80-130", "luxury": "200+"}, "featured": True},
    {"name": "Panama", "capital": "Panama City", "region": "Americas", "subregion": "Central America", "population": 4310000, "currency": "US Dollar (USD)", "language": "Spanish", "timezone": "UTC-5", "safety_level": "caution", "best_time": "Dec-Apr", "budget": {"budget": "45-60", "midrange": "80-130", "luxury": "200+"}, "featured": False},
    {"name": "Guatemala", "capital": "Guatemala City", "region": "Americas", "subregion": "Central America", "population": 16860000, "currency": "Guatemalan Quetzal (GTQ)", "language": "Spanish", "timezone": "UTC-6", "safety_level": "caution", "best_time": "Nov-Apr", "budget": {"budget": "30-40", "midrange": "50-80", "luxury": "120+"}, "featured": False},
    {"name": "Belize", "capital": "Belmopan", "region": "Americas", "subregion": "Central America", "population": 398000, "currency": "Belize Dollar (BZD)", "language": "English", "timezone": "UTC-6", "safety_level": "caution", "best_time": "Dec-May", "budget": {"budget": "50-70", "midrange": "90-140", "luxury": "220+"}, "featured": False},
    {"name": "Nicaragua", "capital": "Managua", "region": "Americas", "subregion": "Central America", "population": 6620000, "currency": "Nicaraguan Cordoba (NIO)", "language": "Spanish", "timezone": "UTC-6", "safety_level": "warning", "best_time": "Dec-Apr", "budget": {"budget": "25-35", "midrange": "45-70", "luxury": "100+"}, "featured": False},
    {"name": "Honduras", "capital": "Tegucigalpa", "region": "Americas", "subregion": "Central America", "population": 9900000, "currency": "Honduran Lempira (HNL)", "language": "Spanish", "timezone": "UTC-6", "safety_level": "warning", "best_time": "Dec-Apr", "budget": {"budget": "30-40", "midrange": "50-80", "luxury": "120+"}, "featured": False},
    {"name": "El Salvador", "capital": "San Salvador", "region": "Americas", "subregion": "Central America", "population": 6490000, "currency": "US Dollar (USD)", "language": "Spanish", "timezone": "UTC-6", "safety_level": "warning", "best_time": "Nov-Apr", "budget": {"budget": "35-45", "midrange": "60-90", "luxury": "140+"}, "featured": False},
    {"name": "Cuba", "capital": "Havana", "region": "Americas", "subregion": "Caribbean", "population": 11330000, "currency": "Cuban Peso (CUP)", "language": "Spanish", "timezone": "UTC-5", "safety_level": "safe", "best_time": "Nov-Apr", "budget": {"budget": "50-70", "midrange": "90-140", "luxury": "220+"}, "featured": False},
    {"name": "Jamaica", "capital": "Kingston", "region": "Americas", "subregion": "Caribbean", "population": 2960000, "currency": "Jamaican Dollar (JMD)", "language": "English", "timezone": "UTC-5", "safety_level": "warning", "best_time": "Dec-Apr", "budget": {"budget": "60-80", "midrange": "110-170", "luxury": "280+"}, "featured": False},
    {"name": "Dominican Republic", "capital": "Santo Domingo", "region": "Americas", "subregion": "Caribbean", "population": 10850000, "currency": "Dominican Peso (DOP)", "language": "Spanish", "timezone": "UTC-4", "safety_level": "caution", "best_time": "Dec-Apr", "budget": {"budget": "50-70", "midrange": "90-140", "luxury": "220+"}, "featured": False},
    {"name": "Puerto Rico", "capital": "San Juan", "region": "Americas", "subregion": "Caribbean", "population": 3290000, "currency": "US Dollar (USD)", "language": "Spanish", "timezone": "UTC-4", "safety_level": "caution", "best_time": "Dec-Apr", "budget": {"budget": "80-110", "midrange": "140-210", "luxury": "350+"}, "featured": False},
    {"name": "Colombia", "capital": "Bogota", "region": "Americas", "subregion": "South America", "population": 50880000, "currency": "Colombian Peso (COP)", "language": "Spanish", "timezone": "UTC-5", "safety_level": "caution", "best_time": "Dec-Mar, Jul-Aug", "budget": {"budget": "35-50", "midrange": "60-100", "luxury": "150+"}, "featured": True},
    {"name": "Peru", "capital": "Lima", "region": "Americas", "subregion": "South America", "population": 32970000, "currency": "Peruvian Sol (PEN)", "language": "Spanish", "timezone": "UTC-5", "safety_level": "caution", "best_time": "May-Sep", "budget": {"budget": "35-50", "midrange": "70-110", "luxury": "180+"}, "featured": True},
    {"name": "Ecuador", "capital": "Quito", "region": "Americas", "subregion": "South America", "population": 17640000, "currency": "US Dollar (USD)", "language": "Spanish", "timezone": "UTC-5", "safety_level": "caution", "best_time": "Jun-Sep", "budget": {"budget": "35-50", "midrange": "60-90", "luxury": "140+"}, "featured": False},
    {"name": "Brazil", "capital": "Brasilia", "region": "Americas", "subregion": "South America", "population": 212600000, "currency": "Brazilian Real (BRL)", "language": "Portuguese", "timezone": "UTC-3 to -5", "safety_level": "caution", "best_time": "Apr-Oct", "budget": {"budget": "45-65", "midrange": "80-130", "luxury": "220+"}, "featured": True},
    {"name": "Argentina", "capital": "Buenos Aires", "region": "Americas", "subregion": "South America", "population": 45200000, "currency": "Argentine Peso (ARS)", "language": "Spanish", "timezone": "UTC-3", "safety_level": "caution", "best_time": "Oct-Apr", "budget": {"budget": "40-60", "midrange": "70-120", "luxury": "200+"}, "featured": True},
    {"name": "Chile", "capital": "Santiago", "region": "Americas", "subregion": "South America", "population": 19120000, "currency": "Chilean Peso (CLP)", "language": "Spanish", "timezone": "UTC-4", "safety_level": "safe", "best_time": "Nov-Mar", "budget": {"budget": "50-70", "midrange": "90-140", "luxury": "240+"}, "featured": False},
    {"name": "Bolivia", "capital": "Sucre", "region": "Americas", "subregion": "South America", "population": 11670000, "currency": "Bolivian Boliviano (BOB)", "language": "Spanish", "timezone": "UTC-4", "safety_level": "caution", "best_time": "May-Oct", "budget": {"budget": "25-35", "midrange": "45-70", "luxury": "100+"}, "featured": False},
    {"name": "Uruguay", "capital": "Montevideo", "region": "Americas", "subregion": "South America", "population": 3470000, "currency": "Uruguayan Peso (UYU)", "language": "Spanish", "timezone": "UTC-3", "safety_level": "safe", "best_time": "Dec-Mar", "budget": {"budget": "55-75", "midrange": "100-150", "luxury": "260+"}, "featured": False},
    {"name": "Paraguay", "capital": "Asuncion", "region": "Americas", "subregion": "South America", "population": 7130000, "currency": "Paraguayan Guarani (PYG)", "language": "Spanish", "timezone": "UTC-4", "safety_level": "caution", "best_time": "May-Sep", "budget": {"budget": "30-45", "midrange": "55-85", "luxury": "140+"}, "featured": False},

    # Africa
    {"name": "Morocco", "capital": "Rabat", "region": "Africa", "subregion": "Northern Africa", "population": 36910000, "currency": "Moroccan Dirham (MAD)", "language": "Arabic", "timezone": "UTC+1", "safety_level": "caution", "best_time": "Mar-May, Sep-Nov", "budget": {"budget": "30-45", "midrange": "60-90", "luxury": "150+"}, "featured": True},
    {"name": "Egypt", "capital": "Cairo", "region": "Africa", "subregion": "Northern Africa", "population": 102300000, "currency": "Egyptian Pound (EGP)", "language": "Arabic", "timezone": "UTC+2", "safety_level": "caution", "best_time": "Oct-Apr", "budget": {"budget": "25-40", "midrange": "50-80", "luxury": "150+"}, "featured": True},
    {"name": "South Africa", "capital": "Pretoria", "region": "Africa", "subregion": "Southern Africa", "population": 59310000, "currency": "South African Rand (ZAR)", "language": "Afrikaans", "timezone": "UTC+2", "safety_level": "caution", "best_time": "May-Sep", "budget": {"budget": "50-70", "midrange": "90-140", "luxury": "240+"}, "featured": True},
    {"name": "Kenya", "capital": "Nairobi", "region": "Africa", "subregion": "Eastern Africa", "population": 53770000, "currency": "Kenyan Shilling (KES)", "language": "Swahili", "timezone": "UTC+3", "safety_level": "caution", "best_time": "Jul-Oct", "budget": {"budget": "40-60", "midrange": "80-130", "luxury": "250+"}, "featured": False},
    {"name": "Tanzania", "capital": "Dodoma", "region": "Africa", "subregion": "Eastern Africa", "population": 59730000, "currency": "Tanzanian Shilling (TZS)", "language": "Swahili", "timezone": "UTC+3", "safety_level": "caution", "best_time": "Jun-Oct", "budget": {"budget": "45-65", "midrange": "90-150", "luxury": "300+"}, "featured": False},
    {"name": "Rwanda", "capital": "Kigali", "region": "Africa", "subregion": "Eastern Africa", "population": 12950000, "currency": "Rwandan Franc (RWF)", "language": "Kinyarwanda", "timezone": "UTC+2", "safety_level": "safe", "best_time": "Jun-Sep", "budget": {"budget": "50-70", "midrange": "100-160", "luxury": "350+"}, "featured": False},
    {"name": "Ethiopia", "capital": "Addis Ababa", "region": "Africa", "subregion": "Eastern Africa", "population": 115000000, "currency": "Ethiopian Birr (ETB)", "language": "Amharic", "timezone": "UTC+3", "safety_level": "caution", "best_time": "Oct-Mar", "budget": {"budget": "30-45", "midrange": "55-85", "luxury": "140+"}, "featured": False},
    {"name": "Ghana", "capital": "Accra", "region": "Africa", "subregion": "Western Africa", "population": 31070000, "currency": "Ghanaian Cedi (GHS)", "language": "English", "timezone": "UTC+0", "safety_level": "caution", "best_time": "Nov-Mar", "budget": {"budget": "35-50", "midrange": "65-100", "luxury": "170+"}, "featured": False},
    {"name": "Senegal", "capital": "Dakar", "region": "Africa", "subregion": "Western Africa", "population": 16740000, "currency": "West African CFA Franc (XOF)", "language": "French", "timezone": "UTC+0", "safety_level": "caution", "best_time": "Nov-May", "budget": {"budget": "40-55", "midrange": "70-110", "luxury": "180+"}, "featured": False},
    {"name": "Namibia", "capital": "Windhoek", "region": "Africa", "subregion": "Southern Africa", "population": 2540000, "currency": "Namibian Dollar (NAD)", "language": "English", "timezone": "UTC+2", "safety_level": "safe", "best_time": "May-Oct", "budget": {"budget": "60-80", "midrange": "110-170", "luxury": "300+"}, "featured": False},
    {"name": "Botswana", "capital": "Gaborone", "region": "Africa", "subregion": "Southern Africa", "population": 2350000, "currency": "Botswana Pula (BWP)", "language": "English", "timezone": "UTC+2", "safety_level": "safe", "best_time": "May-Oct", "budget": {"budget": "70-100", "midrange": "130-200", "luxury": "400+"}, "featured": False},
    {"name": "Zimbabwe", "capital": "Harare", "region": "Africa", "subregion": "Eastern Africa", "population": 14860000, "currency": "US Dollar (USD)", "language": "English", "timezone": "UTC+2", "safety_level": "caution", "best_time": "May-Oct", "budget": {"budget": "50-70", "midrange": "90-140", "luxury": "250+"}, "featured": False},
    {"name": "Zambia", "capital": "Lusaka", "region": "Africa", "subregion": "Eastern Africa", "population": 18380000, "currency": "Zambian Kwacha (ZMW)", "language": "English", "timezone": "UTC+2", "safety_level": "caution", "best_time": "May-Oct", "budget": {"budget": "50-70", "midrange": "90-140", "luxury": "250+"}, "featured": False},
    {"name": "Mauritius", "capital": "Port Louis", "region": "Africa", "subregion": "Eastern Africa", "population": 1270000, "currency": "Mauritian Rupee (MUR)", "language": "English", "timezone": "UTC+4", "safety_level": "safe", "best_time": "May-Dec", "budget": {"budget": "70-100", "midrange": "130-200", "luxury": "350+"}, "featured": False},
    {"name": "Tunisia", "capital": "Tunis", "region": "Africa", "subregion": "Northern Africa", "population": 11820000, "currency": "Tunisian Dinar (TND)", "language": "Arabic", "timezone": "UTC+1", "safety_level": "caution", "best_time": "Mar-May, Sep-Nov", "budget": {"budget": "35-50", "midrange": "65-100", "luxury": "170+"}, "featured": False},
    {"name": "Uganda", "capital": "Kampala", "region": "Africa", "subregion": "Eastern Africa", "population": 45740000, "currency": "Ugandan Shilling (UGX)", "language": "English", "timezone": "UTC+3", "safety_level": "caution", "best_time": "Jun-Sep, Dec-Feb", "budget": {"budget": "35-55", "midrange": "70-120", "luxury": "200+"}, "featured": False},
    {"name": "Madagascar", "capital": "Antananarivo", "region": "Africa", "subregion": "Eastern Africa", "population": 27690000, "currency": "Malagasy Ariary (MGA)", "language": "French", "timezone": "UTC+3", "safety_level": "caution", "best_time": "Apr-Nov", "budget": {"budget": "30-50", "midrange": "60-100", "luxury": "180+"}, "featured": False},
    {"name": "Mozambique", "capital": "Maputo", "region": "Africa", "subregion": "Eastern Africa", "population": 31260000, "currency": "Mozambican Metical (MZN)", "language": "Portuguese", "timezone": "UTC+2", "safety_level": "caution", "best_time": "May-Nov", "budget": {"budget": "35-55", "midrange": "70-120", "luxury": "200+"}, "featured": False},
    {"name": "Malawi", "capital": "Lilongwe", "region": "Africa", "subregion": "Eastern Africa", "population": 19130000, "currency": "Malawian Kwacha (MWK)", "language": "English", "timezone": "UTC+2", "safety_level": "caution", "best_time": "May-Oct", "budget": {"budget": "30-50", "midrange": "60-100", "luxury": "170+"}, "featured": False},
    {"name": "Ivory Coast", "capital": "Yamoussoukro", "region": "Africa", "subregion": "Western Africa", "population": 26380000, "currency": "West African CFA Franc (XOF)", "language": "French", "timezone": "UTC+0", "safety_level": "caution", "best_time": "Nov-Mar", "budget": {"budget": "40-60", "midrange": "80-130", "luxury": "220+"}, "featured": False},
    {"name": "Cameroon", "capital": "Yaounde", "region": "Africa", "subregion": "Middle Africa", "population": 26540000, "currency": "Central African CFA Franc (XAF)", "language": "French", "timezone": "UTC+1", "safety_level": "warning", "best_time": "Nov-Feb", "budget": {"budget": "35-55", "midrange": "70-110", "luxury": "190+"}, "featured": False},
    {"name": "Angola", "capital": "Luanda", "region": "Africa", "subregion": "Middle Africa", "population": 32870000, "currency": "Angolan Kwanza (AOA)", "language": "Portuguese", "timezone": "UTC+1", "safety_level": "caution", "best_time": "May-Oct", "budget": {"budget": "80-120", "midrange": "150-230", "luxury": "380+"}, "featured": False},
    {"name": "Niger", "capital": "Niamey", "region": "Africa", "subregion": "Western Africa", "population": 24210000, "currency": "West African CFA Franc (XOF)", "language": "French", "timezone": "UTC+1", "safety_level": "warning", "best_time": "Nov-Feb", "budget": {"budget": "30-45", "midrange": "55-90", "luxury": "150+"}, "featured": False},
    {"name": "Mali", "capital": "Bamako", "region": "Africa", "subregion": "Western Africa", "population": 20250000, "currency": "West African CFA Franc (XOF)", "language": "French", "timezone": "UTC+0", "safety_level": "warning", "best_time": "Nov-Feb", "budget": {"budget": "30-45", "midrange": "55-90", "luxury": "150+"}, "featured": False},
    {"name": "Burkina Faso", "capital": "Ouagadougou", "region": "Africa", "subregion": "Western Africa", "population": 20900000, "currency": "West African CFA Franc (XOF)", "language": "French", "timezone": "UTC+0", "safety_level": "warning", "best_time": "Nov-Feb", "budget": {"budget": "30-45", "midrange": "55-90", "luxury": "150+"}, "featured": False},
    {"name": "Benin", "capital": "Porto-Novo", "region": "Africa", "subregion": "Western Africa", "population": 12120000, "currency": "West African CFA Franc (XOF)", "language": "French", "timezone": "UTC+1", "safety_level": "caution", "best_time": "Nov-Mar", "budget": {"budget": "35-50", "midrange": "60-100", "luxury": "170+"}, "featured": False},
    {"name": "Togo", "capital": "Lome", "region": "Africa", "subregion": "Western Africa", "population": 8280000, "currency": "West African CFA Franc (XOF)", "language": "French", "timezone": "UTC+0", "safety_level": "caution", "best_time": "Nov-Mar", "budget": {"budget": "30-45", "midrange": "55-90", "luxury": "150+"}, "featured": False},
    {"name": "Liberia", "capital": "Monrovia", "region": "Africa", "subregion": "Western Africa", "population": 5060000, "currency": "Liberian Dollar (LRD)", "language": "English", "timezone": "UTC+0", "safety_level": "warning", "best_time": "Nov-Apr", "budget": {"budget": "50-70", "midrange": "90-140", "luxury": "240+"}, "featured": False},
    {"name": "Sierra Leone", "capital": "Freetown", "region": "Africa", "subregion": "Western Africa", "population": 7980000, "currency": "Sierra Leonean Leone (SLL)", "language": "English", "timezone": "UTC+0", "safety_level": "caution", "best_time": "Nov-Apr", "budget": {"budget": "50-70", "midrange": "90-140", "luxury": "240+"}, "featured": False},
    {"name": "Guinea", "capital": "Conakry", "region": "Africa", "subregion": "Western Africa", "population": 13130000, "currency": "Guinean Franc (GNF)", "language": "French", "timezone": "UTC+0", "safety_level": "warning", "best_time": "Nov-Apr", "budget": {"budget": "40-60", "midrange": "75-120", "luxury": "200+"}, "featured": False},
    {"name": "Gambia", "capital": "Banjul", "region": "Africa", "subregion": "Western Africa", "population": 2420000, "currency": "Gambian Dalasi (GMD)", "language": "English", "timezone": "UTC+0", "safety_level": "caution", "best_time": "Nov-May", "budget": {"budget": "35-50", "midrange": "60-100", "luxury": "170+"}, "featured": False},
    {"name": "Cape Verde", "capital": "Praia", "region": "Africa", "subregion": "Western Africa", "population": 556000, "currency": "Cape Verdean Escudo (CVE)", "language": "Portuguese", "timezone": "UTC-1", "safety_level": "safe", "best_time": "Nov-Jun", "budget": {"budget": "50-70", "midrange": "90-140", "luxury": "240+"}, "featured": False},
    {"name": "Sao Tome and Principe", "capital": "Sao Tome", "region": "Africa", "subregion": "Middle Africa", "population": 219159, "currency": "Sao Tome and Principe Dobra (STN)", "language": "Portuguese", "timezone": "UTC+0", "safety_level": "safe", "best_time": "Jun-Sep", "budget": {"budget": "60-80", "midrange": "100-160", "luxury": "280+"}, "featured": False},
    {"name": "Equatorial Guinea", "capital": "Malabo", "region": "Africa", "subregion": "Middle Africa", "population": 1403000, "currency": "Central African CFA Franc (XAF)", "language": "Spanish", "timezone": "UTC+1", "safety_level": "caution", "best_time": "Jun-Sep", "budget": {"budget": "100-140", "midrange": "180-280", "luxury": "450+"}, "featured": False},
    {"name": "Gabon", "capital": "Libreville", "region": "Africa", "subregion": "Middle Africa", "population": 2230000, "currency": "Central African CFA Franc (XAF)", "language": "French", "timezone": "UTC+1", "safety_level": "caution", "best_time": "Jun-Sep", "budget": {"budget": "80-120", "midrange": "150-230", "luxury": "380+"}, "featured": False},
    {"name": "Republic of the Congo", "capital": "Brazzaville", "region": "Africa", "subregion": "Middle Africa", "population": 5520000, "currency": "Central African CFA Franc (XAF)", "language": "French", "timezone": "UTC+1", "safety_level": "caution", "best_time": "Jun-Sep", "budget": {"budget": "60-90", "midrange": "120-180", "luxury": "300+"}, "featured": False},
    {"name": "DR Congo", "capital": "Kinshasa", "region": "Africa", "subregion": "Middle Africa", "population": 89560000, "currency": "Congolese Franc (CDF)", "language": "French", "timezone": "UTC+1", "safety_level": "warning", "best_time": "Jun-Sep", "budget": {"budget": "50-80", "midrange": "100-160", "luxury": "280+"}, "featured": False},
    {"name": "Central African Republic", "capital": "Bangui", "region": "Africa", "subregion": "Middle Africa", "population": 4830000, "currency": "Central African CFA Franc (XAF)", "language": "French", "timezone": "UTC+1", "safety_level": "danger", "best_time": "Dec-Mar", "budget": {"budget": "50-70", "midrange": "90-140", "luxury": "240+"}, "featured": False},
    {"name": "Chad", "capital": "NDjamena", "region": "Africa", "subregion": "Middle Africa", "population": 16430000, "currency": "Central African CFA Franc (XAF)", "language": "French", "timezone": "UTC+1", "safety_level": "warning", "best_time": "Nov-Mar", "budget": {"budget": "50-70", "midrange": "90-140", "luxury": "240+"}, "featured": False},
    {"name": "Sudan", "capital": "Khartoum", "region": "Africa", "subregion": "Northern Africa", "population": 43850000, "currency": "Sudanese Pound (SDG)", "language": "Arabic", "timezone": "UTC+2", "safety_level": "warning", "best_time": "Oct-Feb", "budget": {"budget": "40-60", "midrange": "80-130", "luxury": "220+"}, "featured": False},
    {"name": "South Sudan", "capital": "Juba", "region": "Africa", "subregion": "Eastern Africa", "population": 11190000, "currency": "South Sudanese Pound (SSP)", "language": "English", "timezone": "UTC+2", "safety_level": "danger", "best_time": "Dec-Mar", "budget": {"budget": "80-120", "midrange": "150-230", "luxury": "380+"}, "featured": False},
    {"name": "Eritrea", "capital": "Asmara", "region": "Africa", "subregion": "Eastern Africa", "population": 3550000, "currency": "Eritrean Nakfa (ERN)", "language": "Tigrinya", "timezone": "UTC+3", "safety_level": "warning", "best_time": "Oct-Mar", "budget": {"budget": "35-50", "midrange": "60-100", "luxury": "170+"}, "featured": False},
    {"name": "Djibouti", "capital": "Djibouti", "region": "Africa", "subregion": "Eastern Africa", "population": 988000, "currency": "Djiboutian Franc (DJF)", "language": "French", "timezone": "UTC+3", "safety_level": "caution", "best_time": "Nov-Mar", "budget": {"budget": "60-90", "midrange": "120-180", "luxury": "300+"}, "featured": False},
    {"name": "Somalia", "capital": "Mogadishu", "region": "Africa", "subregion": "Eastern Africa", "population": 15890000, "currency": "Somali Shilling (SOS)", "language": "Somali", "timezone": "UTC+3", "safety_level": "danger", "best_time": "Dec-Mar", "budget": {"budget": "40-60", "midrange": "80-130", "luxury": "220+"}, "featured": False},
    {"name": "Comoros", "capital": "Moroni", "region": "Africa", "subregion": "Eastern Africa", "population": 870000, "currency": "Comorian Franc (KMF)", "language": "Arabic", "timezone": "UTC+3", "safety_level": "caution", "best_time": "May-Oct", "budget": {"budget": "50-70", "midrange": "90-140", "luxury": "240+"}, "featured": False},
    {"name": "Seychelles", "capital": "Victoria", "region": "Africa", "subregion": "Eastern Africa", "population": 98347, "currency": "Seychellois Rupee (SCR)", "language": "Seselwa Creole", "timezone": "UTC+4", "safety_level": "safe", "best_time": "Apr-May, Oct-Nov", "budget": {"budget": "100-150", "midrange": "200-300", "luxury": "500+"}, "featured": True},
    {"name": "Lesotho", "capital": "Maseru", "region": "Africa", "subregion": "Southern Africa", "population": 2140000, "currency": "Lesotho Loti (LSL)", "language": "English", "timezone": "UTC+2", "safety_level": "caution", "best_time": "Apr-Oct", "budget": {"budget": "40-60", "midrange": "80-130", "luxury": "220+"}, "featured": False},
    {"name": "Eswatini", "capital": "Mbabane", "region": "Africa", "subregion": "Southern Africa", "population": 1160000, "currency": "Swazi Lilangeni (SZL)", "language": "English", "timezone": "UTC+2", "safety_level": "caution", "best_time": "May-Sep", "budget": {"budget": "50-70", "midrange": "90-140", "luxury": "240+"}, "featured": False},
    {"name": "Burundi", "capital": "Gitega", "region": "Africa", "subregion": "Eastern Africa", "population": 11890000, "currency": "Burundian Franc (BIF)", "language": "French", "timezone": "UTC+2", "safety_level": "warning", "best_time": "Jun-Sep", "budget": {"budget": "30-45", "midrange": "55-90", "luxury": "150+"}, "featured": False},
    {"name": "Algeria", "capital": "Algiers", "region": "Africa", "subregion": "Northern Africa", "population": 43850000, "currency": "Algerian Dinar (DZD)", "language": "Arabic", "timezone": "UTC+1", "safety_level": "caution", "best_time": "Mar-May, Sep-Nov", "budget": {"budget": "40-60", "midrange": "80-130", "luxury": "220+"}, "featured": False},
    {"name": "Libya", "capital": "Tripoli", "region": "Africa", "subregion": "Northern Africa", "population": 6870000, "currency": "Libyan Dinar (LYD)", "language": "Arabic", "timezone": "UTC+2", "safety_level": "danger", "best_time": "Mar-May, Sep-Nov", "budget": {"budget": "50-70", "midrange": "90-140", "luxury": "240+"}, "featured": False},

    # Caribbean (Additional)
    {"name": "Bahamas", "capital": "Nassau", "region": "Americas", "subregion": "Caribbean", "population": 393244, "currency": "Bahamian Dollar (BSD)", "language": "English", "timezone": "UTC-5", "safety_level": "caution", "best_time": "Dec-May", "budget": {"budget": "100-150", "midrange": "200-300", "luxury": "500+"}, "featured": False},
    {"name": "Barbados", "capital": "Bridgetown", "region": "Americas", "subregion": "Caribbean", "population": 287375, "currency": "Barbadian Dollar (BBD)", "language": "English", "timezone": "UTC-4", "safety_level": "safe", "best_time": "Dec-May", "budget": {"budget": "80-120", "midrange": "160-240", "luxury": "400+"}, "featured": False},
    {"name": "Trinidad and Tobago", "capital": "Port of Spain", "region": "Americas", "subregion": "Caribbean", "population": 1399488, "currency": "Trinidad and Tobago Dollar (TTD)", "language": "English", "timezone": "UTC-4", "safety_level": "caution", "best_time": "Jan-May", "budget": {"budget": "60-90", "midrange": "120-180", "luxury": "300+"}, "featured": False},
    {"name": "Saint Lucia", "capital": "Castries", "region": "Americas", "subregion": "Caribbean", "population": 183627, "currency": "East Caribbean Dollar (XCD)", "language": "English", "timezone": "UTC-4", "safety_level": "safe", "best_time": "Jan-Apr", "budget": {"budget": "80-120", "midrange": "160-240", "luxury": "400+"}, "featured": False},
    {"name": "Grenada", "capital": "St Georges", "region": "Americas", "subregion": "Caribbean", "population": 112523, "currency": "East Caribbean Dollar (XCD)", "language": "English", "timezone": "UTC-4", "safety_level": "safe", "best_time": "Dec-Apr", "budget": {"budget": "70-100", "midrange": "140-210", "luxury": "350+"}, "featured": False},
    {"name": "Saint Vincent and the Grenadines", "capital": "Kingstown", "region": "Americas", "subregion": "Caribbean", "population": 110940, "currency": "East Caribbean Dollar (XCD)", "language": "English", "timezone": "UTC-4", "safety_level": "safe", "best_time": "Dec-May", "budget": {"budget": "70-100", "midrange": "140-210", "luxury": "350+"}, "featured": False},
    {"name": "Antigua and Barbuda", "capital": "Saint Johns", "region": "Americas", "subregion": "Caribbean", "population": 97929, "currency": "East Caribbean Dollar (XCD)", "language": "English", "timezone": "UTC-4", "safety_level": "safe", "best_time": "Dec-Apr", "budget": {"budget": "90-130", "midrange": "180-270", "luxury": "450+"}, "featured": False},
    {"name": "Dominica", "capital": "Roseau", "region": "Americas", "subregion": "Caribbean", "population": 71986, "currency": "East Caribbean Dollar (XCD)", "language": "English", "timezone": "UTC-4", "safety_level": "safe", "best_time": "Nov-May", "budget": {"budget": "60-90", "midrange": "120-180", "luxury": "300+"}, "featured": False},
    {"name": "Saint Kitts and Nevis", "capital": "Basseterre", "region": "Americas", "subregion": "Caribbean", "population": 53199, "currency": "East Caribbean Dollar (XCD)", "language": "English", "timezone": "UTC-4", "safety_level": "safe", "best_time": "Dec-Apr", "budget": {"budget": "80-120", "midrange": "160-240", "luxury": "400+"}, "featured": False},
    {"name": "Haiti", "capital": "Port-au-Prince", "region": "Americas", "subregion": "Caribbean", "population": 11400000, "currency": "Haitian Gourde (HTG)", "language": "French", "timezone": "UTC-5", "safety_level": "danger", "best_time": "Nov-Mar", "budget": {"budget": "40-60", "midrange": "80-130", "luxury": "220+"}, "featured": False},
    {"name": "Curacao", "capital": "Willemstad", "region": "Americas", "subregion": "Caribbean", "population": 164093, "currency": "Netherlands Antillean Guilder (ANG)", "language": "Dutch", "timezone": "UTC-4", "safety_level": "safe", "best_time": "Year-round", "budget": {"budget": "80-120", "midrange": "160-240", "luxury": "400+"}, "featured": False},
    {"name": "Aruba", "capital": "Oranjestad", "region": "Americas", "subregion": "Caribbean", "population": 106766, "currency": "Aruban Florin (AWG)", "language": "Dutch", "timezone": "UTC-4", "safety_level": "safe", "best_time": "Year-round", "budget": {"budget": "90-130", "midrange": "180-270", "luxury": "450+"}, "featured": False},
    {"name": "Cayman Islands", "capital": "George Town", "region": "Americas", "subregion": "Caribbean", "population": 65722, "currency": "Cayman Islands Dollar (KYD)", "language": "English", "timezone": "UTC-5", "safety_level": "safe", "best_time": "Nov-Apr", "budget": {"budget": "150-220", "midrange": "280-400", "luxury": "650+"}, "featured": False},
    {"name": "Turks and Caicos", "capital": "Cockburn Town", "region": "Americas", "subregion": "Caribbean", "population": 38717, "currency": "US Dollar (USD)", "language": "English", "timezone": "UTC-5", "safety_level": "safe", "best_time": "Nov-May", "budget": {"budget": "120-180", "midrange": "240-360", "luxury": "600+"}, "featured": False},
    {"name": "British Virgin Islands", "capital": "Road Town", "region": "Americas", "subregion": "Caribbean", "population": 30231, "currency": "US Dollar (USD)", "language": "English", "timezone": "UTC-4", "safety_level": "safe", "best_time": "Dec-Apr", "budget": {"budget": "120-180", "midrange": "240-360", "luxury": "600+"}, "featured": False},
    {"name": "US Virgin Islands", "capital": "Charlotte Amalie", "region": "Americas", "subregion": "Caribbean", "population": 104425, "currency": "US Dollar (USD)", "language": "English", "timezone": "UTC-4", "safety_level": "caution", "best_time": "Dec-Apr", "budget": {"budget": "100-150", "midrange": "200-300", "luxury": "500+"}, "featured": False},

    # Central Asia
    {"name": "Kazakhstan", "capital": "Astana", "region": "Asia", "subregion": "Central Asia", "population": 18750000, "currency": "Kazakhstani Tenge (KZT)", "language": "Kazakh", "timezone": "UTC+5/+6", "safety_level": "caution", "best_time": "Apr-Jun, Sep-Oct", "budget": {"budget": "40-60", "midrange": "80-130", "luxury": "220+"}, "featured": False},
    {"name": "Uzbekistan", "capital": "Tashkent", "region": "Asia", "subregion": "Central Asia", "population": 34230000, "currency": "Uzbekistani Som (UZS)", "language": "Uzbek", "timezone": "UTC+5", "safety_level": "caution", "best_time": "Apr-Jun, Sep-Oct", "budget": {"budget": "30-50", "midrange": "60-100", "luxury": "180+"}, "featured": False},
    {"name": "Kyrgyzstan", "capital": "Bishkek", "region": "Asia", "subregion": "Central Asia", "population": 6520000, "currency": "Kyrgyzstani Som (KGS)", "language": "Kyrgyz", "timezone": "UTC+6", "safety_level": "caution", "best_time": "Jun-Sep", "budget": {"budget": "25-40", "midrange": "50-80", "luxury": "150+"}, "featured": False},
    {"name": "Tajikistan", "capital": "Dushanbe", "region": "Asia", "subregion": "Central Asia", "population": 9540000, "currency": "Tajikistani Somoni (TJS)", "language": "Tajik", "timezone": "UTC+5", "safety_level": "caution", "best_time": "Jun-Sep", "budget": {"budget": "25-40", "midrange": "50-80", "luxury": "150+"}, "featured": False},
    {"name": "Turkmenistan", "capital": "Ashgabat", "region": "Asia", "subregion": "Central Asia", "population": 6030000, "currency": "Turkmenistani Manat (TMT)", "language": "Turkmen", "timezone": "UTC+5", "safety_level": "caution", "best_time": "Apr-Jun, Sep-Nov", "budget": {"budget": "40-60", "midrange": "80-130", "luxury": "220+"}, "featured": False},
    {"name": "Mongolia", "capital": "Ulaanbaatar", "region": "Asia", "subregion": "Eastern Asia", "population": 3280000, "currency": "Mongolian Tugrik (MNT)", "language": "Mongolian", "timezone": "UTC+8", "safety_level": "caution", "best_time": "Jun-Sep", "budget": {"budget": "35-55", "midrange": "70-120", "luxury": "200+"}, "featured": False},
    {"name": "Georgia", "capital": "Tbilisi", "region": "Asia", "subregion": "Western Asia", "population": 3710000, "currency": "Georgian Lari (GEL)", "language": "Georgian", "timezone": "UTC+4", "safety_level": "safe", "best_time": "May-Jun, Sep-Oct", "budget": {"budget": "35-50", "midrange": "60-100", "luxury": "170+"}, "featured": True},
    {"name": "Armenia", "capital": "Yerevan", "region": "Asia", "subregion": "Western Asia", "population": 2960000, "currency": "Armenian Dram (AMD)", "language": "Armenian", "timezone": "UTC+4", "safety_level": "safe", "best_time": "May-Jun, Sep-Oct", "budget": {"budget": "30-45", "midrange": "55-90", "luxury": "160+"}, "featured": False},
    {"name": "Azerbaijan", "capital": "Baku", "region": "Asia", "subregion": "Western Asia", "population": 10140000, "currency": "Azerbaijani Manat (AZN)", "language": "Azerbaijani", "timezone": "UTC+4", "safety_level": "caution", "best_time": "Apr-Jun, Sep-Oct", "budget": {"budget": "40-60", "midrange": "80-130", "luxury": "220+"}, "featured": False},
    {"name": "Lebanon", "capital": "Beirut", "region": "Asia", "subregion": "Western Asia", "population": 6820000, "currency": "Lebanese Pound (LBP)", "language": "Arabic", "timezone": "UTC+2", "safety_level": "warning", "best_time": "Apr-Jun, Sep-Nov", "budget": {"budget": "50-70", "midrange": "90-140", "luxury": "250+"}, "featured": False},
    {"name": "Iran", "capital": "Tehran", "region": "Asia", "subregion": "Southern Asia", "population": 83990000, "currency": "Iranian Rial (IRR)", "language": "Persian", "timezone": "UTC+3:30", "safety_level": "caution", "best_time": "Mar-May, Sep-Nov", "budget": {"budget": "25-40", "midrange": "50-80", "luxury": "150+"}, "featured": False},
    {"name": "Iraq", "capital": "Baghdad", "region": "Asia", "subregion": "Western Asia", "population": 40220000, "currency": "Iraqi Dinar (IQD)", "language": "Arabic", "timezone": "UTC+3", "safety_level": "danger", "best_time": "Oct-Apr", "budget": {"budget": "40-60", "midrange": "80-130", "luxury": "220+"}, "featured": False},
    {"name": "Kuwait", "capital": "Kuwait City", "region": "Asia", "subregion": "Western Asia", "population": 4270000, "currency": "Kuwaiti Dinar (KWD)", "language": "Arabic", "timezone": "UTC+3", "safety_level": "safe", "best_time": "Nov-Mar", "budget": {"budget": "80-120", "midrange": "160-240", "luxury": "400+"}, "featured": False},
    {"name": "Yemen", "capital": "Sanaa", "region": "Asia", "subregion": "Western Asia", "population": 29830000, "currency": "Yemeni Rial (YER)", "language": "Arabic", "timezone": "UTC+3", "safety_level": "danger", "best_time": "Dec-Mar", "budget": {"budget": "30-45", "midrange": "55-90", "luxury": "150+"}, "featured": False},
    {"name": "Afghanistan", "capital": "Kabul", "region": "Asia", "subregion": "Southern Asia", "population": 38930000, "currency": "Afghan Afghani (AFN)", "language": "Dari", "timezone": "UTC+4:30", "safety_level": "danger", "best_time": "Apr-Jun, Sep-Nov", "budget": {"budget": "25-40", "midrange": "50-80", "luxury": "150+"}, "featured": False},
    {"name": "Bhutan", "capital": "Thimphu", "region": "Asia", "subregion": "Southern Asia", "population": 771610, "currency": "Bhutanese Ngultrum (BTN)", "language": "Dzongkha", "timezone": "UTC+6", "safety_level": "safe", "best_time": "Mar-May, Sep-Nov", "budget": {"budget": "200-250", "midrange": "250-350", "luxury": "500+"}, "featured": False},
    {"name": "Brunei", "capital": "Bandar Seri Begawan", "region": "Asia", "subregion": "South-Eastern Asia", "population": 437479, "currency": "Brunei Dollar (BND)", "language": "Malay", "timezone": "UTC+8", "safety_level": "safe", "best_time": "Feb-Oct", "budget": {"budget": "50-70", "midrange": "90-140", "luxury": "250+"}, "featured": False},
    {"name": "Timor-Leste", "capital": "Dili", "region": "Asia", "subregion": "South-Eastern Asia", "population": 1318442, "currency": "US Dollar (USD)", "language": "Portuguese", "timezone": "UTC+9", "safety_level": "caution", "best_time": "May-Nov", "budget": {"budget": "40-60", "midrange": "80-130", "luxury": "220+"}, "featured": False},
    {"name": "North Korea", "capital": "Pyongyang", "region": "Asia", "subregion": "Eastern Asia", "population": 25780000, "currency": "North Korean Won (KPW)", "language": "Korean", "timezone": "UTC+9", "safety_level": "warning", "best_time": "Apr-Jun, Sep-Oct", "budget": {"budget": "60-100", "midrange": "150-250", "luxury": "400+"}, "featured": False},
    {"name": "Macau", "capital": "Macau", "region": "Asia", "subregion": "Eastern Asia", "population": 649100, "currency": "Macanese Pataca (MOP)", "language": "Chinese", "timezone": "UTC+8", "safety_level": "safe", "best_time": "Oct-Dec", "budget": {"budget": "70-100", "midrange": "130-200", "luxury": "350+"}, "featured": False},

    # Europe (Additional)
    {"name": "Andorra", "capital": "Andorra la Vella", "region": "Europe", "subregion": "Southern Europe", "population": 77265, "currency": "Euro (EUR)", "language": "Catalan", "timezone": "UTC+1", "safety_level": "safe", "best_time": "Jun-Sep, Dec-Mar", "budget": {"budget": "80-110", "midrange": "140-210", "luxury": "350+"}, "featured": False},
    {"name": "San Marino", "capital": "San Marino", "region": "Europe", "subregion": "Southern Europe", "population": 33931, "currency": "Euro (EUR)", "language": "Italian", "timezone": "UTC+1", "safety_level": "safe", "best_time": "Apr-Oct", "budget": {"budget": "70-100", "midrange": "130-200", "luxury": "330+"}, "featured": False},
    {"name": "Liechtenstein", "capital": "Vaduz", "region": "Europe", "subregion": "Western Europe", "population": 38128, "currency": "Swiss Franc (CHF)", "language": "German", "timezone": "UTC+1", "safety_level": "safe", "best_time": "Jun-Sep, Dec-Mar", "budget": {"budget": "120-160", "midrange": "200-300", "luxury": "550+"}, "featured": False},
    {"name": "Kosovo", "capital": "Pristina", "region": "Europe", "subregion": "Southeastern Europe", "population": 1870000, "currency": "Euro (EUR)", "language": "Albanian", "timezone": "UTC+1", "safety_level": "caution", "best_time": "May-Sep", "budget": {"budget": "30-45", "midrange": "55-90", "luxury": "150+"}, "featured": False},
    {"name": "Moldova", "capital": "Chisinau", "region": "Europe", "subregion": "Eastern Europe", "population": 2620000, "currency": "Moldovan Leu (MDL)", "language": "Romanian", "timezone": "UTC+2", "safety_level": "caution", "best_time": "May-Sep", "budget": {"budget": "30-45", "midrange": "55-90", "luxury": "150+"}, "featured": False},
    {"name": "Belarus", "capital": "Minsk", "region": "Europe", "subregion": "Eastern Europe", "population": 9410000, "currency": "Belarusian Ruble (BYN)", "language": "Belarusian", "timezone": "UTC+3", "safety_level": "caution", "best_time": "May-Sep", "budget": {"budget": "35-50", "midrange": "60-100", "luxury": "180+"}, "featured": False},
    {"name": "Ukraine", "capital": "Kyiv", "region": "Europe", "subregion": "Eastern Europe", "population": 43730000, "currency": "Ukrainian Hryvnia (UAH)", "language": "Ukrainian", "timezone": "UTC+2", "safety_level": "danger", "best_time": "May-Sep", "budget": {"budget": "30-45", "midrange": "55-90", "luxury": "150+"}, "featured": False},
    {"name": "Russia", "capital": "Moscow", "region": "Europe", "subregion": "Eastern Europe", "population": 145900000, "currency": "Russian Ruble (RUB)", "language": "Russian", "timezone": "UTC+3 to +12", "safety_level": "caution", "best_time": "May-Sep", "budget": {"budget": "50-70", "midrange": "90-140", "luxury": "280+"}, "featured": False},
    {"name": "Gibraltar", "capital": "Gibraltar", "region": "Europe", "subregion": "Southern Europe", "population": 33691, "currency": "Gibraltar Pound (GIP)", "language": "English", "timezone": "UTC+1", "safety_level": "safe", "best_time": "Apr-Oct", "budget": {"budget": "80-110", "midrange": "140-210", "luxury": "350+"}, "featured": False},
    {"name": "Faroe Islands", "capital": "Torshavn", "region": "Europe", "subregion": "Northern Europe", "population": 52903, "currency": "Danish Krone (DKK)", "language": "Faroese", "timezone": "UTC+0", "safety_level": "safe", "best_time": "Jun-Aug", "budget": {"budget": "100-140", "midrange": "180-270", "luxury": "450+"}, "featured": False},

    # South America (Additional)
    {"name": "Venezuela", "capital": "Caracas", "region": "Americas", "subregion": "South America", "population": 28440000, "currency": "Venezuelan Bolivar (VES)", "language": "Spanish", "timezone": "UTC-4", "safety_level": "danger", "best_time": "Dec-Apr", "budget": {"budget": "30-50", "midrange": "60-100", "luxury": "180+"}, "featured": False},
    {"name": "Guyana", "capital": "Georgetown", "region": "Americas", "subregion": "South America", "population": 786552, "currency": "Guyanese Dollar (GYD)", "language": "English", "timezone": "UTC-4", "safety_level": "caution", "best_time": "Feb-Apr, Aug-Nov", "budget": {"budget": "50-70", "midrange": "90-140", "luxury": "240+"}, "featured": False},
    {"name": "Suriname", "capital": "Paramaribo", "region": "Americas", "subregion": "South America", "population": 586632, "currency": "Surinamese Dollar (SRD)", "language": "Dutch", "timezone": "UTC-3", "safety_level": "caution", "best_time": "Feb-Apr, Aug-Nov", "budget": {"budget": "50-70", "midrange": "90-140", "luxury": "240+"}, "featured": False},
    {"name": "French Guiana", "capital": "Cayenne", "region": "Americas", "subregion": "South America", "population": 298682, "currency": "Euro (EUR)", "language": "French", "timezone": "UTC-3", "safety_level": "caution", "best_time": "Jul-Nov", "budget": {"budget": "80-120", "midrange": "160-240", "luxury": "400+"}, "featured": False},
    {"name": "Falkland Islands", "capital": "Stanley", "region": "Americas", "subregion": "South America", "population": 3480, "currency": "Falkland Islands Pound (FKP)", "language": "English", "timezone": "UTC-3", "safety_level": "safe", "best_time": "Oct-Mar", "budget": {"budget": "100-150", "midrange": "200-300", "luxury": "500+"}, "featured": False},

    # Oceania
    {"name": "Australia", "capital": "Canberra", "region": "Oceania", "subregion": "Australia and New Zealand", "population": 25690000, "currency": "Australian Dollar (AUD)", "language": "English", "timezone": "UTC+8 to +11", "safety_level": "safe", "best_time": "Sep-Nov, Mar-May", "budget": {"budget": "90-120", "midrange": "150-230", "luxury": "400+"}, "featured": True},
    {"name": "New Zealand", "capital": "Wellington", "region": "Oceania", "subregion": "Australia and New Zealand", "population": 5080000, "currency": "New Zealand Dollar (NZD)", "language": "English", "timezone": "UTC+12", "safety_level": "safe", "best_time": "Dec-Mar", "budget": {"budget": "85-115", "midrange": "150-220", "luxury": "380+"}, "featured": True},
    {"name": "Fiji", "capital": "Suva", "region": "Oceania", "subregion": "Melanesia", "population": 896000, "currency": "Fijian Dollar (FJD)", "language": "English", "timezone": "UTC+12", "safety_level": "safe", "best_time": "May-Oct", "budget": {"budget": "70-100", "midrange": "130-200", "luxury": "350+"}, "featured": False},
    {"name": "Papua New Guinea", "capital": "Port Moresby", "region": "Oceania", "subregion": "Melanesia", "population": 8950000, "currency": "Papua New Guinean Kina (PGK)", "language": "English", "timezone": "UTC+10", "safety_level": "warning", "best_time": "May-Oct", "budget": {"budget": "60-90", "midrange": "110-170", "luxury": "280+"}, "featured": False},
    {"name": "Vanuatu", "capital": "Port Vila", "region": "Oceania", "subregion": "Melanesia", "population": 307150, "currency": "Vanuatu Vatu (VUV)", "language": "Bislama", "timezone": "UTC+11", "safety_level": "safe", "best_time": "Apr-Oct", "budget": {"budget": "70-100", "midrange": "130-200", "luxury": "300+"}, "featured": False},
    {"name": "Solomon Islands", "capital": "Honiara", "region": "Oceania", "subregion": "Melanesia", "population": 686878, "currency": "Solomon Islands Dollar (SBD)", "language": "English", "timezone": "UTC+11", "safety_level": "caution", "best_time": "Apr-Nov", "budget": {"budget": "80-110", "midrange": "150-220", "luxury": "350+"}, "featured": False},
    {"name": "Samoa", "capital": "Apia", "region": "Oceania", "subregion": "Polynesia", "population": 198410, "currency": "Samoan Tala (WST)", "language": "Samoan", "timezone": "UTC+13", "safety_level": "safe", "best_time": "May-Oct", "budget": {"budget": "60-90", "midrange": "110-170", "luxury": "280+"}, "featured": False},
    {"name": "Tonga", "capital": "Nukualofa", "region": "Oceania", "subregion": "Polynesia", "population": 105697, "currency": "Tongan Paanga (TOP)", "language": "Tongan", "timezone": "UTC+13", "safety_level": "safe", "best_time": "May-Oct", "budget": {"budget": "70-100", "midrange": "130-190", "luxury": "300+"}, "featured": False},
    {"name": "Micronesia", "capital": "Palikir", "region": "Oceania", "subregion": "Micronesia", "population": 115023, "currency": "US Dollar (USD)", "language": "English", "timezone": "UTC+10", "safety_level": "safe", "best_time": "Dec-Apr", "budget": {"budget": "80-110", "midrange": "150-220", "luxury": "350+"}, "featured": False},
    {"name": "Palau", "capital": "Ngerulmud", "region": "Oceania", "subregion": "Micronesia", "population": 18094, "currency": "US Dollar (USD)", "language": "Palauan", "timezone": "UTC+9", "safety_level": "safe", "best_time": "Nov-Apr", "budget": {"budget": "100-140", "midrange": "180-260", "luxury": "400+"}, "featured": False},
    {"name": "Marshall Islands", "capital": "Majuro", "region": "Oceania", "subregion": "Micronesia", "population": 59190, "currency": "US Dollar (USD)", "language": "Marshallese", "timezone": "UTC+12", "safety_level": "safe", "best_time": "Dec-Apr", "budget": {"budget": "90-120", "midrange": "160-240", "luxury": "380+"}, "featured": False},
    {"name": "Kiribati", "capital": "Tarawa", "region": "Oceania", "subregion": "Micronesia", "population": 119449, "currency": "Australian Dollar (AUD)", "language": "Gilbertese", "timezone": "UTC+12", "safety_level": "safe", "best_time": "Apr-Oct", "budget": {"budget": "80-110", "midrange": "150-220", "luxury": "340+"}, "featured": False},
    {"name": "Nauru", "capital": "Yaren", "region": "Oceania", "subregion": "Micronesia", "population": 10834, "currency": "Australian Dollar (AUD)", "language": "Nauruan", "timezone": "UTC+12", "safety_level": "safe", "best_time": "Year-round", "budget": {"budget": "100-140", "midrange": "180-260", "luxury": "400+"}, "featured": False},
    {"name": "Tuvalu", "capital": "Funafuti", "region": "Oceania", "subregion": "Polynesia", "population": 11792, "currency": "Australian Dollar (AUD)", "language": "Tuvaluan", "timezone": "UTC+12", "safety_level": "safe", "best_time": "May-Oct", "budget": {"budget": "90-130", "midrange": "170-250", "luxury": "380+"}, "featured": False},
    {"name": "French Polynesia", "capital": "Papeete", "region": "Oceania", "subregion": "Polynesia", "population": 280904, "currency": "CFP Franc (XPF)", "language": "French", "timezone": "UTC-10", "safety_level": "safe", "best_time": "May-Oct", "budget": {"budget": "120-170", "midrange": "220-340", "luxury": "600+"}, "featured": True},
    {"name": "New Caledonia", "capital": "Noumea", "region": "Oceania", "subregion": "Melanesia", "population": 285498, "currency": "CFP Franc (XPF)", "language": "French", "timezone": "UTC+11", "safety_level": "safe", "best_time": "Sep-Nov", "budget": {"budget": "100-140", "midrange": "180-270", "luxury": "420+"}, "featured": False},
    {"name": "Cook Islands", "capital": "Avarua", "region": "Oceania", "subregion": "Polynesia", "population": 17564, "currency": "New Zealand Dollar (NZD)", "language": "English", "timezone": "UTC-10", "safety_level": "safe", "best_time": "Apr-Nov", "budget": {"budget": "90-130", "midrange": "170-260", "luxury": "400+"}, "featured": False},

    # Middle East
    {"name": "United Arab Emirates", "capital": "Abu Dhabi", "region": "Asia", "subregion": "Western Asia", "population": 9890000, "currency": "UAE Dirham (AED)", "language": "Arabic", "timezone": "UTC+4", "safety_level": "safe", "best_time": "Nov-Mar", "budget": {"budget": "100-140", "midrange": "180-280", "luxury": "500+"}, "featured": False},
    {"name": "Israel", "capital": "Jerusalem", "region": "Asia", "subregion": "Western Asia", "population": 9220000, "currency": "Israeli New Shekel (ILS)", "language": "Hebrew", "timezone": "UTC+2", "safety_level": "caution", "best_time": "Mar-May, Sep-Nov", "budget": {"budget": "90-120", "midrange": "160-240", "luxury": "420+"}, "featured": False},
    {"name": "Jordan", "capital": "Amman", "region": "Asia", "subregion": "Western Asia", "population": 10200000, "currency": "Jordanian Dinar (JOD)", "language": "Arabic", "timezone": "UTC+2", "safety_level": "caution", "best_time": "Mar-May, Sep-Nov", "budget": {"budget": "50-70", "midrange": "90-140", "luxury": "250+"}, "featured": False},
    {"name": "Oman", "capital": "Muscat", "region": "Asia", "subregion": "Western Asia", "population": 5110000, "currency": "Omani Rial (OMR)", "language": "Arabic", "timezone": "UTC+4", "safety_level": "safe", "best_time": "Oct-Mar", "budget": {"budget": "80-110", "midrange": "140-210", "luxury": "380+"}, "featured": False},
    {"name": "Qatar", "capital": "Doha", "region": "Asia", "subregion": "Western Asia", "population": 2880000, "currency": "Qatari Riyal (QAR)", "language": "Arabic", "timezone": "UTC+3", "safety_level": "safe", "best_time": "Nov-Apr", "budget": {"budget": "100-140", "midrange": "180-280", "luxury": "500+"}, "featured": False},
    {"name": "Bahrain", "capital": "Manama", "region": "Asia", "subregion": "Western Asia", "population": 1700000, "currency": "Bahraini Dinar (BHD)", "language": "Arabic", "timezone": "UTC+3", "safety_level": "safe", "best_time": "Nov-Mar", "budget": {"budget": "80-110", "midrange": "140-210", "luxury": "380+"}, "featured": False},
    {"name": "Saudi Arabia", "capital": "Riyadh", "region": "Asia", "subregion": "Western Asia", "population": 34810000, "currency": "Saudi Riyal (SAR)", "language": "Arabic", "timezone": "UTC+3", "safety_level": "caution", "best_time": "Nov-Feb", "budget": {"budget": "80-110", "midrange": "140-220", "luxury": "400+"}, "featured": False},
]


def process_country(country: dict) -> dict:
    """Process country into standard format."""
    name = country["name"]
    slug = name.lower().replace(" ", "-").replace("'", "")

    budget = country.get("budget", {"budget": "50-80", "midrange": "100-150", "luxury": "200+"})

    return {
        "name": name,
        "slug": slug,
        "official_name": name,
        "cca2": "",
        "cca3": "",
        "region": country.get("region", ""),
        "subregion": country.get("subregion", ""),
        "region_slug": country.get("region", "").lower(),
        "capital": country.get("capital", ""),
        "population": country.get("population", 0),
        "area": 0,
        "currency": country.get("currency", "Local currency"),
        "languages": [country.get("language", "Local language")],
        "language": country.get("language", "Local language"),
        "timezone": country.get("timezone", "UTC"),
        "timezones": [country.get("timezone", "UTC")],
        "flag_emoji": "",
        "flag_svg": "",
        "flag_png": "",
        "coat_of_arms": "",
        "maps_google": "",
        "maps_osm": "",
        "landlocked": False,
        "borders": [],
        "driving_side": "right",
        "calling_code": "",
        "safety_level": country.get("safety_level", "caution"),
        "budget_per_day": budget,
        "best_time_to_visit": country.get("best_time", "Varies"),
        "latlng": [0, 0],
        "capital_latlng": [0, 0],
        "un_member": True,
        "independent": True,
        "featured": country.get("featured", False)
    }


def save_fallback_data():
    """Save fallback country data."""
    DATA_DIR.mkdir(parents=True, exist_ok=True)

    # Process all countries
    processed = [process_country(c) for c in COUNTRIES]
    processed.sort(key=lambda x: x["name"])

    # Save all countries
    all_countries_path = DATA_DIR / "countries.json"
    with open(all_countries_path, "w", encoding="utf-8") as f:
        json.dump(processed, f, indent=2, ensure_ascii=False)

    print(f"Saved {len(processed)} countries to {all_countries_path}")

    # Save individual country files
    countries_dir = DATA_DIR / "countries"
    countries_dir.mkdir(exist_ok=True)

    for country in processed:
        country_path = countries_dir / f"{country['slug']}.json"
        with open(country_path, "w", encoding="utf-8") as f:
            json.dump(country, f, indent=2, ensure_ascii=False)

    return processed


if __name__ == "__main__":
    save_fallback_data()
